-- CREAR TABLA CLIENTE
CREATE TABLE CLIENTE (
	IDCLI INTEGER NOT NULL,
	NOMCLI VARCHAR2(50) NOT NULL,
	APECLI VARCHAR2(50) NOT NULL,
	DIRCLI VARCHAR2(80) NOT NULL,
    EMACLI VARCHAR2(50) UNIQUE NOT NULL,
    DNICLI CHAR(8) UNIQUE NOT NULL,
	CELCLI CHAR(9) NOT NULL,
	CODUBI CHAR(6) NOT NULL,
	ESTCLI CHAR(1) NOT NULL,
	CONSTRAINT CLIENTE_pk PRIMARY KEY(IDCLI)
);

-- CREAR TABLA UBIGEO
CREATE TABLE UBIGEO (
    CODUBI CHAR(6) NOT NULL,
    DEPUBI VARCHAR2(50) NOT NULL,
    PROUBI VARCHAR2(50) NOT NULL,
    DISUBI VARCHAR2(50) NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBI)
);

-- CREAR TABLA DEMO
CREATE TABLE DEMO (
    CAMPO1 VARCHAR2(30) NOT NULL,
    CAMPO2 VARCHAR2(30) NOT NULL,
    CAMPO3 VARCHAR2(30) NOT NULL
);

-- Relacionar la tabla CLIENTE - UBIGEO
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_UBIGEO FOREIGN KEY (CODUBI) REFERENCES UBIGEO (CODUBI);

-- CREAR LAS SECUENCIAS
CREATE SEQUENCE ID_CLIENTE START WITH 1 INCREMENT BY 1 ORDER;


-- CREAR LOS TRIGGERS
CREATE OR REPLACE TRIGGER ID_CLIENTE BEFORE INSERT ON CLIENTE FOR EACH ROW BEGIN SELECT ID_CLIENTE.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
END;
/

-- INSERTAR REGISTROS DE UBIGEO
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150501','LIMA','CAÑETE','SAN VICENTE');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150502','LIMA','CAÑETE','ASIA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150503','LIMA','CAÑETE','CALANGO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150504','LIMA','CAÑETE','CERRO AZUL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150505','LIMA','CAÑETE','CHILCA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150506','LIMA','CAÑETE','COAYLLO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150507','LIMA','CAÑETE','IMPERIAL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150508','LIMA','CAÑETE','LUNAHUANA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150509','LIMA','CAÑETE','MALA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150510','LIMA','CAÑETE','NUEVO IMPERIAL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150511','LIMA','CAÑETE','PACARAN');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150512','LIMA','CAÑETE','QUILMANA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150513','LIMA','CAÑETE','SAN ANTONIO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150514','LIMA','CAÑETE','SAN LUIS');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150515','LIMA','CAÑETE','SANTA CRUZ DE FLORES');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150516','LIMA','CAÑETE','ZUÑIGA');

-- INSERTAR REGISTROS DE CLIENTE
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Juan Gabriel','Condori Jara','Nuevo Hualcara Mz:K Lt:3','juan.condori.jara@vallegrande.edu.pe','45698574','940460321','150501','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Sergio Danilo','Flores Tadeo','San Vicente Mz:J Lt:5','sergio.flores@vallegrande.edu.pe','50398574','948695767','150502','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Josue Miguel','Alarcon Asto','Santa Rosa Mz:T Lt:7','josue@gmail.com','48947854','998475645','150503','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Maria Daniela','Díaz Romero','Imperial Mz:C Lt:9','maria@gmail.com','49589432','903489256','150504','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Diego Alvaro','Galvez Quispe','Las Malvinas Mz:V Lt:2','diego@gmail.com','46087689','919803481','150505','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Lucia Dayana','Cuzcano Cuya','Santa Rosa Mz:E Lt:4','lucia@gmail.com','51289456','989347622','150506','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Victor Raúl','Quispe Manturano','San Luis Mz:G Lt:6','victor@gmail.com','55904785','998143568','150507','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Sofia Carmen','Huamán Vásquez','San Antonio Mz:R Lt:3','sofia@gmail.com','49745632','932457821','150508','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Kevin Rodrigo','Guerra Cáceres','Nuevo Imperial Mz:F Lt:6','kevin@gmail.com','48563483','998436512','150509','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Brayan Enrique','Vicente Manrique','Mala Mz:N Lt:8','brayan@gmail.com','47846370','956734563','150510','A');

-- Vista de Clientes Activos
CREATE VIEW vClienteA
AS
SELECT
	 C.IDCLI AS IDCLI,
     INITCAP(C.NOMCLI) AS NOMCLI,
     INITCAP(C.APECLI) AS APECLI,
     INITCAP(C.DIRCLI) AS DIRCLI,
     C.EMACLI AS EMACLI,
	 C.DNICLI AS DNICLI,
	 C.CELCLI AS CELCLI,
	 U.DISUBI AS DISUBI,
	 ROW_NUMBER() OVER (ORDER BY C.IDCLI DESC) AS ORDEN
FROM 
     CLIENTE C
	 INNER JOIN UBIGEO U ON
	 C.CODUBI = U.CODUBI
WHERE 
     C.ESTCLI = 'A';

-- Vista de Clientes Inactivos
CREATE VIEW vClienteI
AS
SELECT
	 C.IDCLI AS IDCLI,
     INITCAP(C.NOMCLI) AS NOMCLI,
     INITCAP(C.APECLI) AS APECLI,
     INITCAP(C.DIRCLI) AS DIRCLI,
     C.EMACLI AS EMACLI,
	 C.DNICLI AS DNICLI,
	 C.CELCLI AS CELCLI,
	 U.DISUBI AS DISUBI,
	 ROW_NUMBER() OVER (ORDER BY C.IDCLI DESC) AS ORDEN
FROM 
     CLIENTE C
	 INNER JOIN UBIGEO U ON
	 C.CODUBI = U.CODUBI
WHERE 
     C.ESTCLI = 'I';

-- Vista de todos los Clientes Activos|Inactivos
CREATE VIEW vClienteT
AS
SELECT
	 C.IDCLI AS IDCLI,
     INITCAP(C.NOMCLI) AS NOMCLI,
     INITCAP(C.APECLI) AS APECLI,
     INITCAP(C.DIRCLI) AS DIRCLI,
     C.EMACLI AS EMACLI,
	 C.DNICLI AS DNICLI,
	 C.CELCLI AS CELCLI,
	 U.DISUBI AS DISUBI,
	 ROW_NUMBER() OVER (ORDER BY C.IDCLI DESC) AS ORDEN
FROM 
     CLIENTE C
	 INNER JOIN UBIGEO U ON
	 C.CODUBI = U.CODUBI;
